name: Deploy to LEMP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository auschecken
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Deploy auf den Server
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /path/to/your/app
          git pull origin main
          # Optionale Schritte, z.B.:
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx
