name: Deploy PHP App to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # IP-Adresse des DigitalOcean-Servers
      SERVER_IP: ${{ secrets.SERVER_IP }}
      # SSH-Benutzername
      SSH_USER: ${{ secrets.SSH_USER }}
      # Pfad auf dem Server, in dem die Anwendung bereitgestellt wird
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      # Schritt 1: Repository auschecken
      - name: Check out the repository
        uses: actions/checkout@v2

      # Schritt 2: PHP-Abhängigkeiten installieren (optional, falls Composer genutzt wird)
      - name: Install PHP Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli unzip
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer install --no-dev --no-scripts --no-interaction --prefer-dist --optimize-autoloader

      # Schritt 3: Übertragung per SSH (mit rsync)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Anwendungspfad erstellen (falls nicht existierend)
            mkdir -p $DEPLOY_PATH
            # Bestehende Dateien überschreiben
            rsync -avz --delete --exclude=".git" ./ $SSH_USER@$SERVER_IP:$DEPLOY_PATH

      # Schritt 4: Nginx und PHP-FPM neu starten
      - name: Restart Nginx and PHP-FPM
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
            sudo systemctl restart php8.0-fpm

      # Schritt 5: Erfolgsnachricht
      - name: Deployment successful
        run: echo "Deployment to DigitalOcean server $SERVER_IP successful!"
